# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b41383d2356a50a6ed39b3f0ba03552c077e50d78e4a03225a49a6382e29b3e6573bf347f429c89c75cc4ab996bbbacef194bd5b9b5c81486bcf7dd60bb30707

test:
  secret_key_base: 800be07fa789ef4fa7a5b4a1347d8e2509214891533e9c5cfcefac4daaa77640b8e35c94b783f813afcdf59944c0d3bb9d1c29fd4366b9e80109023a360b8a46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
